### ISSUE TITLE
Question: `--no-openmp`, `has_openmp` and OpenBLAS

### ISSUE THREAD

**Issue by piyueh** [nv-legate/legate.numpy#30]
Whether OpenBLAS will be built with OpenMP or not is determined by the result of function `has_openmp()`. The result of `has_openmp()` depends on `g++` compilation outcome. That says, even if I use `--no-openmp` to install Legate NumPy, the underlying OpenBLAS is still built with OpenMP (if my `g++` supports it). Is this a designed behavior? Thanks.

**Comment by manopapad** [comment]
As you note, `--no-openmp` affects only the building of legate.numpy itself, not OpenBLAS.

I assume this was done to avoid having to check whether or not OpenBLAS was built with OpenMP support when we want to (re-) build legate.numpy *with* OpenMP support (OpenBLAS would be guaranteed to contain OpenMP support, and legate.numpy could choose to ignore it). @marcinz and @lightsighter would know better.

I changed the code in `has_openm()` to honor the user's setting of `$CXX` instead of always using `g++`.
