### ISSUE TITLE
Garbage collection not working properly

### ISSUE THREAD

**Issue by piyueh** [nv-legate/legate.numpy#33]
## Problem

During loops, memory usage keeps growing when it should keep constant. Looks like a garbage-collection issue.

### Option 1: using `examples/stencil.py` (take more time to see the crash)

1. step 1: go to `legate.numpy/examples/stencil.py`
2. step 2: run `legate --cpus 1 --sysmem 1500 --eager-alloc-percentage 1 ./stencil.py --num 3000 --benchmark 20` (I lower down the system memory to make the out-of-memory happen faster.)

The crash happens at about the 14th benchmark iteration, so to get a profiling result, change `--benchmark` to 13. That is, `legate --profile --cpus 1 --sysmem 1500 --eager-alloc-percentage 1 ./stencil.py --num 3000 --benchmark 13 -lg:numpy:test -lg:inorder`.

Here is the profiling result: [legate_prof.tar.gz](https://github.com/nv-legate/legate.numpy/files/6542208/legate_prof.tar.gz)

### Option 2: using custom code (faster to see the crash)

1. step 1: create `test.py`
   ```python
   from legate import numpy
   
   a0 = numpy.random.random((1004, 1004))
   b0 = numpy.random.random((1004, 1004))
   c0 = numpy.random.random((1004, 1004))

   counter = 0
   while True:
       a = a0.copy()
       b = b0.copy()
       c = c0.copy()

       for i in range(2):
           a[2:-2, i] = a[2:-2, 2].copy()
           b[2:-2, i] = b[2:-2, 2].copy()
           c[2:-2, i] = c[2:-2, 2].copy()
   
       for i in range(-3):
           a[2:-2, i] = a[2:-2, -3].copy()
           b[2:-2, i] = b[2:-2, -3].copy()
           c[2:-2, i] = c[2:-2, -3].copy()
   
       for i in range(2):
           a[i, 2:-2] = a[2, 2:-2].copy()
           b[i, 2:-2] = b[2, 2:-2].copy()
           c[i, 2:-2] = c[2, 2:-2].copy()

       for i in range(-3):
           a[i, 2:-2] = a[-3, 2:-2,].copy()
           b[i, 2:-2] = b[-3, 2:-2,].copy()
           c[i, 2:-2] = c[-3, 2:-2,].copy()

       counter += 1
       print(counter)
   ```
2. step 2: run the script with `legate --cpus 1 --sysmem 750 --eager-alloc-percentage 1 ./test.py`.

The out-of-memory happened at 935th iteration. So to get a profiling output, add `if counter % 934 == 0: break` after `print(counter)`, and then do `legate --profile --cpus 1 --sysmem 750 --eager-alloc-percentage 1 ./test.py -lg:numpy:test -lg:inorder`.

Here's the profiling result: [legate_prof.tar.gz](https://github.com/nv-legate/legate.numpy/files/6542273/legate_prof.tar.gz)

**Comment by marcinz** [comment]
@piyueh Thank you, I was able to replicate the issue. I am looking into it now.

**Comment by lightsighter** [comment]
This is another effect of some code needed to run distributed garbage collection. You can make it go away temporarily by setting the `NUMPY_FIELD_REUSE_FREQ` environment variable to 1. There will be near-zero cost on a single node, but on large scale runs this cost will start to impact scaling.

**Comment by lightsighter** [comment]
So for me at least, setting `NUMPY_FIELD_REUSE_FREQ=1` fixed the problem for both benchmarks. It pegs the sampling frequency for the distributed garbage collection to be performed on every array allocation. On a single node, there should be near-zero overhead for this at least.

**Comment by piyueh** [comment]
For me, `NUMPY_FIELD_REUSE_FREQ=1` only slows down the memory growth, but eventually, the two benchmarks still crashed. The `examples/stencil.py` now runs out of memory at the 57th benchmark iteration, while the dummy test with a lot of `copy`s runs out of memory at iteration 1417 (when using `-lg:numpy:test -lg:inorder`).

I'll test if `NUMPY_FIELD_REUSE_FREQ=1` can make my application run till to the end of simulation.

**Comment by lightsighter** [comment]
Please pull and try again with fe505384b

**Comment by manopapad** [comment]
Leaving an explanation of the issue here, in case anyone runs into this again in the future.

Legate.numpy uses a different field to back each "live" ndarray. After an ndarray gets python garbage-collected, legate.numpy can reuse its field. However, we want all shards to use the same field for each ndarray, and fields can be collected in different orders on different shards. So each shard doesn’t immediately reuse a collected field, instead it puts it in a local queue. Once this queue contains `NUMPY_FIELD_REUSE_FREQ` fields (default 32) [we do a "collective" operation across all shards to determine which fields have been collected on *all* shards](https://github.com/nv-legate/legate.numpy/blob/fe505384bc632d7ce4bc8ec9a07fbcd99ffc71ac/legate/numpy/runtime.py#L276-L297). Only those fields are made available for reuse, in the same order across all shards.

Give the above, we would expect up to `NUMPY_FIELD_REUSE_FREQ` "wasted" fields (collected but not reusable) on each node at any time, but we don't have to do an expensive distributed collection as often. With `NUMPY_FIELD_REUSE_FREQ=1` we do the distributed garbage collection on every array allocation, so there should be no wasted fields.

This situation is made more complicated by the fact that a field is only freed once the ndarray it backs is garbage collected, and for that we are at the mercy of the python garbage collector. This shouldn't be an issue if our data structures don't contain cycles, because then they should be getting collected immediately by python's reference counting mechanism, and we're not waiting for a full garbage collection to detect the unreachable cycles. However, it appears some cycles slipped through, and that's what Mike fixed with fe50538, by replacing some references with weakrefs.

Finally, it's important that the mapper reuses instances for each field (as much as possible), so we don't (generally) have more than one instance per live field (and also for each of `NUMPY_FIELD_REUSE_FREQ` fields queued for distributed collection).

**Comment by lightsighter** [comment]
> This shouldn't be an issue if our data structures don't contain cycles, because then they should be getting collected immediately by python's reference counting mechanism

This isn't quite true. We can do our best to ensure we don't introduce any reference cycles in Legate data structures, but that doesn't preclude the application from having its own data structures that induce a cycle and prevent deterministic collection of arrays. For example, 

```
a -> b
b -> a
a -> array
```

The `a` and `b` objects create a cycle at the application level and `a` also hold a reference to an array. We can't do anything to help that, but the result is the same as what we had before.

> Give the above, we would expect up to NUMPY_FIELD_REUSE_FREQ "wasted" fields (collected but not reusable) on each node at any time,

I wouldn't necessarily say they are wasted. There is often a trade-off here between task-parallelism and amount of memory used. If you put off re-using the fields you can expand the task-parallelism available to be discovered by Legion by spreading more operations across more independent fields. If you re-use fields immediately you are minimizing the memory footprint but limiting the task parallelism that is available to be exploited. It is not obvious what the right trade-off is for each application unless you can see into the future to know better how big the footprint of the application is.

**Comment by piyueh** [comment]
I confirm the two test cases here are working with that commit. And thanks for the explanation!
Feel free to close the issue, or to add more comments!

**Comment by manopapad** [comment]
Adding a correction to the above writeup: We don't actually perform a distributed collection once we've reached `NUMPY_FIELD_REUSE_FREQ` collected fields locally, we do that every `NUMPY_FIELD_REUSE_FREQ` field allocations. Therefore the number of fields that have been collected locally but cannot be reused yet (until we do a distributed collection) is not exactly tied to `NUMPY_FIELD_REUSE_FREQ`, but these counts should be close.
